name: CI Workflow
on:
  push:
    branches:
      - main   # Trigger on push to the 'main' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # The job runs on the latest version of Ubuntu

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Step 2: Set up Node.js (this step is for Node.js projects)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the version of Node.js you want to use
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install   # This will install dependencies defined in package.json

      # Step 4: Run tests
      - name: Run tests
        run: npm test      # This will run tests defined in the "test" script in package.json
deploy:
  runs-on: ubuntu-latest
  needs: build-and-test  # This ensures the deploy job runs only after the build-and-test job finishes
  steps:
    - name: Deploy application
      run: echo 'Deploying application...'
